-- Profiles table linked to Supabase Auth
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    email text,
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Trigger to auto-populate profiles on user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, display_name, email)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
        new.email
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Create profiles for users who already existed before this migration.
insert into public.profiles (id, display_name, email)
select
    users.id,
    coalesce(users.raw_user_meta_data ->> 'full_name', users.email),
    users.email
from auth.users as users
on conflict (id) do nothing;

-- Habits table
create table if not exists public.habits (
    id bigint generated by default as identity primary key,
    profile_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
    name varchar(120) not null,
    icon varchar(16) not null default '◌',
    color varchar(32) not null default 'mint',
    streak integer not null default 0 check (streak >= 0),
    done boolean not null default false,
    frequency varchar(16) not null default 'daily'
        check (frequency in ('daily', 'weekly', 'monthly')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Tasks table
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    profile_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
    title varchar(160) not null,
    tag varchar(64) not null default 'Personal',
    priority varchar(16) not null default 'Medium'
        check (priority in ('High', 'Medium', 'Low')),
    workflow_column varchar(32) not null default 'To do'
        check (workflow_column in ('To do', 'In progress', 'Done')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Events table
create table if not exists public.events (
    id bigint generated by default as identity primary key,
    profile_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
    title varchar(160) not null,
    date date not null,
    time time not null default '09:00:00',
    color varchar(32) not null default 'blue',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Indexes
create index if not exists habits_profile_id_idx on public.habits(profile_id);
create index if not exists tasks_profile_id_idx on public.tasks(profile_id);
create index if not exists events_profile_id_date_idx on public.events(profile_id, date);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.habits enable row level security;
alter table public.tasks enable row level security;
alter table public.events enable row level security;

-- Profiles Policies
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select to authenticated using (id = (select auth.uid()));

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- Habits Policies
drop policy if exists habits_all_own on public.habits;
create policy habits_all_own on public.habits
for all to authenticated
using (profile_id = (select auth.uid()))
with check (profile_id = (select auth.uid()));

-- Tasks Policies
drop policy if exists tasks_all_own on public.tasks;
create policy tasks_all_own on public.tasks
for all to authenticated
using (profile_id = (select auth.uid()))
with check (profile_id = (select auth.uid()));

-- Events Policies
drop policy if exists events_all_own on public.events;
create policy events_all_own on public.events
for all to authenticated
using (profile_id = (select auth.uid()))
with check (profile_id = (select auth.uid()));

-- Updated_at Trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists habits_set_updated_at on public.habits;
create trigger habits_set_updated_at before update on public.habits
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at before update on public.events
for each row execute function public.set_updated_at();