-- Store one daily completion per user-owned habit.
create table if not exists public.habit_completions (
    id bigint generated by default as identity primary key,
    habit_id bigint not null references public.habits(id) on delete cascade,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    completion_date date not null,
    created_at timestamptz not null default now(),
    constraint habit_completions_unique_day
        unique (habit_id, profile_id, completion_date)
);

create index if not exists habit_completions_profile_date_idx
    on public.habit_completions(profile_id, completion_date);

alter table public.habit_completions enable row level security;

drop policy if exists habit_completions_select_own on public.habit_completions;
create policy habit_completions_select_own
on public.habit_completions for select
to authenticated
using (
    profile_id = (select auth.uid())
    and exists (
        select 1 from public.habits
        where habits.id = habit_completions.habit_id
          and habits.profile_id = (select auth.uid())
    )
);

drop policy if exists habit_completions_insert_own on public.habit_completions;
create policy habit_completions_insert_own
on public.habit_completions for insert
to authenticated
with check (
    profile_id = (select auth.uid())
    and exists (
        select 1 from public.habits
        where habits.id = habit_completions.habit_id
          and habits.profile_id = (select auth.uid())
    )
);

drop policy if exists habit_completions_delete_own on public.habit_completions;
create policy habit_completions_delete_own
on public.habit_completions for delete
to authenticated
using (profile_id = (select auth.uid()));
